### ISSUE TITLE
5V제어에 대한 문제점 발생

### ISSUE THREAD

**Issue by mokyabun** [seonghwan7694/Marine_City#10]
## 문제점
LOLIN D1 MINI MCU에 들어가는 ESP8266의 작동전압이 3.3V라서 크레인에 들어가는 5V 전자석을 제어할 수 없습니다.

## 해결법
- 저렴한 12V 전자석 + FET 사용 12V 제어 + LM2596 강하 레귤레이터로 MCU 전원 (12V 전원 사용)
- 5V 전자석 사용 + FET or Transistor 사용 5V 제어 (5V 전원 사용)

\* 3.3에서 5V/12V 제어하는 FET, Transistor 종류는 제가 찾겠습니다.
\* 가격은 전자가 더 저렴할 것으로 보입니다.

**Comment by seonghwan7694** [comment]
아 승압 관련 회로는 여기다가 적어주셨네요. 확인해보겠습니다.

**Comment by mokyabun** [comment]
12, 24V 전자석 + L298N 모터드라이버 사용으로 결정이 난 것 같아 이슈 닫습니다.
