### ISSUE TITLE
컨테이너 운송 로봇 배터리 종류 선정

### ISSUE THREAD

**Issue by mokyabun** [seonghwan7694/Marine_City#11]
어제 이것에 대해서도 회의를 해야했었는데 까먹어서 깃허브 이슈에 올립니다.

## 안건
컨테이너 운송 로봇에 들어가는 배터리를 선정해야합니다.
컨테이너 운송 로봇은 약 10cm x 5cm 정도 사이즈가 될 것 같습니다.

## 배터리의 종류
- 18650 리튬 이온 배터리 (크기 큼, 대중적)
- 리튬 폴리머 배터리 (크기 작음, 가벼움)

**Comment by seonghwan7694** [comment]
Q1. 찾아보니 배터리의 공급전압(?)이 3.7v이던데, 무한 회전 모터의 작동 전압이 3.5v to 6v라니 **1대의 컨테이너 운송 로봇 당 배터리 1개만 있으면 되는지 궁금**합니다.

Q2. 리튬 폴리머 vs 리튬 이온 -> 저는 리튬 폴리머가 좋을 것 같습니다.
리튬 이온 : 제가 찾아본 바로는 2cm * 7cm 가 있었습니다. [링크](https://www.devicemart.co.kr/goods/view?no=12486582)

리튬 폴리머 : 제가 찾아본 바로는 2cm * 5cm (두께 1cm)가 있었습니다. [링크](https://www.devicemart.co.kr/goods/view?no=1376863) 리튬 폴리머 배터리에 대해 간단하게 찾아본 결과, 일반적으로 에너지 밀도가 상대적으로 높고 안정성이 높으며 자연방전과 메모리 현상이 거의 없어 드론에 주로 쓰이는 것이라고 합니다. [링크](https://brunch.co.kr/@dronestarting/809)

**배터리 관리를 잘 해야할 것 같습니다**

Q3. 리튬 폴리머, 리튬 이온 모두 별도의 충전 장치가 필요해보이는데 맞는가요? 리튬 폴리머의 경우 [링크](https://www.devicemart.co.kr/goods/view?no=1278837) 이걸 구매하면 될 것 같습니다. 맞나요?

**Comment by mokyabun** [comment]
> Q1. 찾아보니 배터리의 공급전압(?)이 3.7v이던데, 무한 회전 모터의 작동 전압이 3.5v to 6v라니 **1대의 컨테이너 운송 로봇 당 배터리 1개만 있으면 되는지 궁금**합니다.

이슈 #12 에 3.7V to 5V 전압 승압을 위한 모듈에 대한 내용이 있습니다. 확인해주시면 감사하겠습니다.

> Q2. 리튬 폴리머 vs 리튬 이온 -> 저는 리튬 폴리머가 좋을 것 같습니다. 리튬 이온 : 제가 찾아본 바로는 2cm * 7cm 가 있었습니다. [링크](https://www.devicemart.co.kr/goods/view?no=12486582)

넵 리튬 폴리머가 다양한 크기(작은 크기)가 있어서 좋을 것 같습니다.

> Q3. 리튬 폴리머, 리튬 이온 모두 별도의 충전 장치가 필요해보이는데 맞는가요? 리튬 폴리머의 경우 [링크](https://www.devicemart.co.kr/goods/view?no=1278837) 이걸 구매하면 될 것 같습니다. 맞나요?

Q1과 동일하게 이슈 #12 에 해당 모듈 구매 링크를 적어 놓았습니다.

**Comment by seonghwan7694** [comment]
넵 그러면 리튬 폴리머로 결정할까요? 동의하시면 이슈 닫으면 될 것 같습니다.

**Comment by mokyabun** [comment]
넵 동의합니다.
