### ISSUE TITLE
배터리 충전 및 전압 승압을 위한 모듈 선정

### ISSUE THREAD

**Issue by mokyabun** [seonghwan7694/Marine_City#12]
배터리 충전에는 [TP4056](https://smartstore.naver.com/misoparts/products/5256144442), 5V로의 승압은 [MT3608](https://smartstore.naver.com/misoparts/products/5256524456)을 사용해야 할 것 같은데 확인 부탁드립니다. @seonghwan7694

**Comment by seonghwan7694** [comment]
1. 아 이미 배터리 충전에 대해 언급해주셨네요. 그럼 [이것](https://smartstore.naver.com/misoparts/products/5256144442)으로 알고 있겠습니다. 디바이스 마켓에 비해 더 1천원 정도 저렴한 것 같습니다.

2. 배터리 승압 관련해서 [3.7V to 5V DC-DC Setp up Converter circuit using IC MT3608](https://somanytech.com/3-7v-to-5v-boost-converter-circuit-diagram-dc-dc-buck-converter-schematics/)라는 내용을 보게 되었는데 여기서 나오는 회로대로 조직하면 되는게 맞는지 궁금합니다.

> [Components required]
> Inductor L≥22uH : 제가 모르는 것
> Switching diode (Schottky diode) I=SS34 : 제가 모르는 것
> IC MT3608 series
> 2 ✕ Capacitor C≥22uF : 제가 모르는 것
> R1 = 110kΩ
> R2 = 15kΩ

저는 모르는게 많네요 :<

**Comment by mokyabun** [comment]
> 2. 배터리 승압 관련해서 [3.7V to 5V DC-DC Setp up Converter circuit using IC MT3608](https://somanytech.com/3-7v-to-5v-boost-converter-circuit-diagram-dc-dc-buck-converter-schematics/)라는 내용을 보게 되었는데 여기서 나오는 회로대로 조직하면 되는게 맞는지 궁금합니다.
> 
> > [Components required]
> > Inductor L≥22uH : 제가 모르는 것
> > Switching diode (Schottky diode) I=SS34 : 제가 모르는 것
> > IC MT3608 series
> > 2 ✕ Capacitor C≥22uF : 제가 모르는 것
> > R1 = 110kΩ
> > R2 = 15kΩ
> 
> 저는 모르는게 많네요 :<

링크의 회로는 저희가 구매할 모듈에 이미 모두 내장되어있어서 저희는 신경쓰지 않아도 될 것 같습니다.

**Comment by seonghwan7694** [comment]
이해했습니다. 불량도 있을수 있으니 : [MT3608](https://smartstore.naver.com/misoparts/products/5256524456)는 11개, [TP4056](https://smartstore.naver.com/misoparts/products/5256144442)는 5개(리튬 폴리머 배터리 어떤거 쓸지도 정해야되네요)정도(이전에 IoT 보드를 9개를 사용하기로 결정했음) 견적서에 포함시켜 두겠습니다.

**Comment by mokyabun** [comment]
MT3608 DC-DC 승압 모듈 사용, TP4056 리튬 배터리 충전 모듈 사용으로 결정나서 이슈 닫습니다.
