### ISSUE TITLE
LOLIN D1의 문제점

### ISSUE THREAD

**Issue by mokyabun** [seonghwan7694/Marine_City#13]
## 문제점
검색을 해보니 네이버스토어에서 판매하는 [구형 Wemos D1](https://smartstore.naver.com/misoparts/products/6611022099)에는 Reset과 관련한 문제가 있는 것으로 보입니다. 
(코드 업로드시 리셋이 되어 업로드가 되지 않는 문제인 것 같습니다.) 
(저도 예전에 동일 보드 사용시 일부 몇개의 보드에서 겪었던 문제였습니다.)

## 해결책
사이즈는 좀 크지만 동일 스토어에서 판매하는 [NodeMCU](https://smartstore.naver.com/misoparts/products/5533682195)를 사용하는 것이 안전한 선택일 것 같습니다.

**Comment by seonghwan7694** [comment]
네 알겠습니다. 지금 열심히 승압 회로 들여다 보고 있긴한데 이해가 잘 가지 않습니다. 조금 댓글이 늦더라도 이해 부탁드립니다.

회로를 구상하시면서 선택하게되는 부픔의 가격은 [한컴 스페이스 링크](https://space.malangmalang.com/open?fileId=m:0:1183591128&lang=ko)에서 적어주시면 좋을 것 같습니다.

**Comment by seonghwan7694** [comment]
첨부해주신 NodeMCU에 +1200원인 옵션이 있는데 어떤걸 구매하면 될지 판단 부탁드립니다.

1. CH340 3180원
2. CH340 칩셋 3180 + 1200원

1200원이 추가로 붙는건 [핀헤더](https://www.google.com/search?q=%ED%95%80%ED%97%A4%EB%8D%94&tbm=isch&ved=2ahUKEwi63pTjmrT6AhVeTPUHHVPFB5kQ2-cCegQIABAA&oq=%ED%95%80%ED%97%A4%EB%8D%94&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIGCAAQHhAFMgYIABAeEAUyBggAEB4QBTIGCAAQHhAFOgQIIxAnOgQIABADOgsIABCABBCxAxCDAToICAAQgAQQsQNQ9AVYlQtg3xFoAnAAeAKAAW2IAbEGkgEDMi42mAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=8oUyY7qdNd6Y1e8P04qfyAk&bih=1422&biw=864#imgrc=g44qeFVawMQ9aM)가 있어서 그런걸까요? 구글에 나오는 NodeMCU들은 전부 핀헤더가 디폴트로 붙여있는데...

**Comment by mokyabun** [comment]
CP2102 칩셋으로 업그레이드에 1200원이 추가되는 것 같습니다.(아마 업체에서 오타를 냈거나 재고가 없어 저렇게 표기한 것 같습니다)

**Comment by seonghwan7694** [comment]
그러면 1번으로 견적 내보겠습니다.

**Comment by seonghwan7694** [comment]
구형 D1은 Reset 문제가 있어 NodeMCU로 의견이 모아졌으니 이슈 닫도록 하겠습니다. 수고하셨습니다.
