### ISSUE TITLE
배 관련 내용 부재

### ISSUE THREAD

**Issue by seonghwan7694** [seonghwan7694/Marine_City#14]
지금까지 배에 대한 논의는 하지 않은 걸로 기억합니다.

**Comment by mokyabun** [comment]
## 소재
소재는 배 하우징도 3D 프린터로 출력하면 될 것 같습니다.

## 부품
배용 NodeMCU, 모터드라이버orMOSFET, 모터(or 서보모터(서보 모터 출력이 충분할지 모르겠습니다.) 추가하면 될 것 같습니다.

**Comment by seonghwan7694** [comment]
네. 배에 관해 걱정(아래에 한 껏 적어보겠습니다)이 많지만 잘 부탁드리겠습니다...

1. 과연 물에 뜰 수 있을지 궁금함
2. 특정 좌표에 오랜 시간 머무르는게 가능한지 궁금함
3. 아무래도 물이 유체이다 보니 배의 정확한 조작은 힘들 것 같은데 좋은 아이디어가 있는지

저희 작품이 [유튜브 영상](https://www.youtube.com/watch?v=0tKGmv5ApTE)에 나온대로 되었으면 좋겠네요. 이 영상만 보면 1, 2번 걱정은 사라지는데 3번이 좀 걱정됩니다. 감사합니다.

3번 걱정은 "반 자동화"이면 해결되긴 할 것 같습니다. 사용자가 배를 조종하고 버튼을 눌러 크레인(배 to 컨테이너 로봇)을 작동하게 하고... 그렇습니다.

**Comment by mokyabun** [comment]
배는 우선 DC모터, 서보모터 2종류의 모터를 구매해보고 제작하면서 좀 더 연구 해보는 거로 합시다. 이슈 닫겠습니다.
