### ISSUE TITLE
항구 소재 변경 문의

### ISSUE THREAD

**Issue by mokyabun** [seonghwan7694/Marine_City#15]
## 문의 내용
아크릴이 비싸서 바다만 아크릴로 제단하고 항구의 바닥은 [포맥스 원판 3T](https://www.devicemart.co.kr/goods/view?no=13182227&market=naver&NaPm=ct%3Dl8jr8y08%7Cci%3D9bb4f5fb3805c5853bfab69906fb10d94fff90f1%7Ctr%3Dslsl%7Csn%3D876973%7Chk%3Defbb8fa9aa7a2dcdf0b90cfb8bfe1e1bcece3eff)를 구매하여 직접 재단하는게 좋아보이는데 어떻게 생각하시나요?

**Comment by seonghwan7694** [comment]
전체를 아크릴(2T)로 했을 때 56,300원 정도 나옵니다. 어제 했던 견적 사이트와 다른 곳에서 견적을 내보았습니다.

'바다 아크릴 재단(2T) + 항구 A, B, C 포맥스(3T)'로 견적 내보고 댓글 수정해보겠습니다.

**Comment by mokyabun** [comment]
<img width="875" alt="스크린샷 2022-09-27 시간: 15 01 09" src="https://user-images.githubusercontent.com/37375701/192445273-a7ccf6f3-ce30-440e-9e4e-ce4f663b483f.png">

바다 아크릴 + 3T 포맥스 원판 사용시 약 39000원 정도 나옵니다.

**Comment by seonghwan7694** [comment]
네 그러면 줄여보도록 합시다

**Comment by mokyabun** [comment]
#16 에서 말한 것 처럼 포맥스 판 2개 구입시 약 54000원 정도 나오는데 이러면 그냥 전부 아크릴로 하는것이 좋지 않을까요? 라고 말하려고 Re-open 했는데 다른 추가적인 요인 (ex. 크레인 레일) 같은걸 추가하려면 포맥스가 나을 것 같네요. 다시 이슈 닫겠습니다.
