### ISSUE TITLE
임시 견적

### ISSUE THREAD

**Issue by mokyabun** [seonghwan7694/Marine_City#16]
<img width="875" alt="스크린샷 2022-09-27 시간: 15 02 36" src="https://user-images.githubusercontent.com/37375701/192445478-b19785b2-a175-4b06-9131-703e96253e38.png">

임시로 엑셀을 사용하여 견적을 내봤습니다. 배 부품+예비 부품 제외 약 14만원정도 나오네요.

**Comment by mokyabun** [comment]
<img width="880" alt="스크린샷 2022-09-27 시간: 14 50 54" src="https://user-images.githubusercontent.com/37375701/192445749-8441b2ff-8c59-425a-a54a-8047cccb4726.png">

**Comment by seonghwan7694** [comment]
아크릴은 2T 맞을까요?
저희가 부품 신청서 쓸 때 옵션까지 정확하게 써야해서 자세하게 적어주시면 좋을 것 같습니다.

![ssss](https://user-images.githubusercontent.com/93508637/192446833-96a4a459-26ee-4f98-a74b-cffd29e5093b.png)

**Comment by mokyabun** [comment]
> 아크릴은 2T 맞을까요?
> 저희가 부품 신청서 쓸 때 옵션까지 정확하게 써야해서 자세하게 적어주시면 좋을 것 같습니다.

넵 2T로 어제 회의에서 보여주신 사이트로 견적냈습니다. 한글 파일에는 자세하게 적겠습니다.

**Comment by mokyabun** [comment]
MOSFET같은 부품은 좀 더 조사를 해보고 추가하도록 하겠습니다. 대부분 1000원보다 싸서 견적에는 큰 변화는 없을 것 같습니다.

**Comment by seonghwan7694** [comment]
제가 계산을 잘못했을 수 있는데
![ssss](https://user-images.githubusercontent.com/93508637/192448282-04482487-120b-4edc-97b5-9bcef4f441b3.png)
단순 넓이로만 계산했을 때(재단시에 손실이 없다고 가정할 때) 포맥스 2개가 필요할 것 같습니다.

**Comment by seonghwan7694** [comment]
회로 부분은 잘 부탁드립니다 (꾸벅)

**Comment by mokyabun** [comment]
항구는 어차피 바다 부분의 아크릴에 붙여서 사용할거고 3개로도 충분히 지탱이 가능할거라 생각하여 65 * 15판은 3개로 계산했습니다.
(3개로 계산하면 판 1개로 제작이 가능하긴 합니다.)

하지만 설계도를 그려보니 남는 부분이 거의 없어서 그냥 포맥스판 2개를 구입하는 것도 좋아보입니다.

**Comment by mokyabun** [comment]
<img width="927" alt="스크린샷 2022-09-27 시간: 22 50 46" src="https://user-images.githubusercontent.com/37375701/192545077-abad6af9-4a81-42a0-b744-4a5c4851e210.png">

최대한 가격을 줄여봤는데 12000원 정도가 초과됩니다... 줄일 수 있는게 있을까요? @seonghwan7694

**Comment by mokyabun** [comment]
ESP12-CAM은 컨테이너 저장시 어떤 컨테이너인지 QR코드 같은걸 사용해 판별하는 기능을 추가하면 좋을 것 같아서 넣었습니다. 어떻게 생각하시나요?

**Comment by seonghwan7694** [comment]
확인했습니다. 20분정도 이내로 생각해보고 코멘트 남기도록하겠습니다. 수고하셨습니다 :)

**Comment by seonghwan7694** [comment]
1. NodeMCU : 항구 3개로 만드는걸로 결정한 것 같았는데 비용 문제때문에 2개로 줄이셨는지요. (방금 3개 맞다는 카톡 확인했습니다.) 숫자가 맞지 않는 것 같습니다. 각 항구 당 4개가 쓰이고, 배가 1개를 소모하는걸로 알고 있습니다. 제 계산으로는 총 13개가 맞습니다.
2. ESP32-CAM : 저는 괜찮다고 생각합니다. 그러나, 잘 이해가지 않는 부분이 있습니다. 카메라를 어디에 부착할 건지 알려주시면 좋을 것 같습니다. 예를들어, {육지 to 배달 로봇}에서 사용한다던지. 타워 크레인에서 사용하는건지. 부품 고장을 우려하여 여유분도 구매하는 것인지.. 넵 그렇습니다
3. 아크릴 - 바다 : 많이 논의했던 사항이니 넘어가도록 하겠습니다. 
4. 공유기 : 이전에 논의했던 사항이니 넘어가도록 하겠습니다.
5. 포맥스 3T 4등분 :  어차피 등분된걸 이어붙이면 되니 이 부분은 문제삼지 않겠습니다. 아마 1개로는 충분하지 않을 것 같은데, 비용 문제때문에 1개로 줄이신거라고 이해하고 있겠습니다. 계산은 안 해봤지만, 항구의 벽 2면에 포맥스를 안 붙일 계획이라면 1개로 가능할 것 같습니다.
6. 공유기 : 이전에 논의했던 사항이니 넘어가도록 하겠습니다.
7. 점퍼선 : 넘어가도록 하겠습니다.
8. L293D 모터 드라이버 : 간단하게 알아보았습니다. 두 개의 모터를 독립적으로 제어할 수 있다는 내용을 봤습니다.
9. 비었음
10. MT3608 승압 : 이전에 논의했던 사항이니 넘어가도록 하겠습니다.
11. TP4056 충전 : 이전에 논의했던 사항이니 넘어가도록 하겠습니다.
12. 360도 서보모터 : 12개 적여주셨는데요. 크레인은 스텝 모터를 사용하는게 좋을 것 같다고 하셨는데 운송 로봇에 쓰이는 것일까요? 각 항구당 운송 로봇은 2대, 이륜으로 생각하면 수량이 맞습니다.
13. 가민 18650 1200mah : 리튬 폴리머 배터리로 논의해왔었는데 바뀌었네요. 혹시 이유를 들을 수 있을까요?
14. 적외선 센서 모듈 : **판매처 링크**랑 **어디에 부착해 쓸 예정이신지** 설명부탁드립니다.
15. 배터리 홀더 : 리튬 이온 배터리로 바뀌면서 추가된 부분인 것 같습니다.
16. 비었음
17. 3v 소형 DC 모터 : **판매처 링크**랑 수량이 2개인데 **어디에서 & 어떤 역할로 쓸 예정이신지** 설명부탁드립니다. 아마 배일 것 같긴합니다.
18. LM2596S 강하형 스텝다운 : 지금까지 회의에서 전압을 낮추는 회로를 논의한 적이 없었는데 추가한 계기가 궁금합니다.
19. 전자석 12v : 각 항구당 2개, 총 3개항구를 제작하니 개수가 맞습니다.
20. ULN2003 모터 드라이버 모듈 + 5v 스텝 모터 : 아마 모터 드라이버 모듈은 8번에서 구매하신 것 같은데 스텝 모터때문에 구매하시는건가요? (제가 제대로된 판단은 못 하겠지만) 역시 판매처 링크 알려주시면 좋을 것같습니다.

좀 내용이 많은데 혹시 시간 되시면 조용히(부모님이 주무시고 계셔서) 줌을 하거나 아님 내일도 이슈로 토론하고 내일 저녁 8시쯤에 톡방에 올리는게 좋을 것 같습니다. 수고하셨습니다 ㅠㅠ

**Comment by mokyabun** [comment]
> 1. NodeMCU : 항구 3개로 만드는걸로 결정한 것 같았는데 비용 문제때문에 2개로 줄이셨는지요. (방금 3개 맞다는 카톡 확인했습니다.) 숫자가 맞지 않는 것 같습니다. 각 항구 당 4개가 쓰이고, 배가 1개를 소모하는걸로 알고 있습니다. 제 계산으로는 총 13개가 맞습니다.

넵 제 실수였던 것 같습니다. NodeMCU가 1개 추가되어야 하는게 맞습니다.

> 2. ESP32-CAM : 저는 괜찮다고 생각합니다. 그러나, 잘 이해가지 않는 부분이 있습니다. 카메라를 어디에 부착할 건지 알려주시면 좋을 것 같습니다. 예를들어, {육지 to 배달 로봇}에서 사용한다던지. 타워 크레인에서 사용하는건지. 부품 고장을 우려하여 여유분도 구매하는 것인지.. 넵 그렇습니다

배 + 저장용 크레인에 사용할 예정입니다. 배에는 위치 판단+고정에 사용할 예정이고, 저장용 크레인에는 컨테이너 관리(어떤 컨테이너가 들어오고 나가는지)에 사용할 예정입니다. 따라서 총 4개 추가하였습니다. (ESP8266 + OV2640이 같이 있는 MCU입니다.) 하지만 1개는 코드 업로드용 어댑터 있는거로 추가했어야 했는데 깜빡했습니다. (약 3000원 추가됩니다.)

> 5. 포맥스 3T 4등분 :  어차피 등분된걸 이어붙이면 되니 이 부분은 문제삼지 않겠습니다. 아마 1개로는 충분하지 않을 것 같은데, 비용 문제때문에 1개로 줄이신거라고 이해하고 있겠습니다. 계산은 안 해봤지만, 항구의 벽 2면에 포맥스를 안 붙일 계획이라면 1개로 가능할 것 같습니다.

이건 책상 다리와 같은 형태로 제작하면 충분한 사이즈일 것 같기도 하고 말씀하신대로 예산문제 때문에 1개로 줄였습니다. 제작시 더 필요하면 추가 구매 신청하여 더 구매하면 될 것 같습니다.

> 8. L293D 모터 드라이버 : 간단하게 알아보았습니다. 두 개의 모터를 독립적으로 제어할 수 있다는 내용을 봤습니다.

전자석을 어떻게 작동시키면 좋을까 생각하다가 많이 사용해본 모터 드라이버를 사용하는 것이 좋을 것 같아서 추가하였습니다. 또한 배의 모터 구동에도 사용할 예정입니다.

> 12. 360도 서보모터 : 12개 적여주셨는데요. 크레인은 스텝 모터를 사용하는게 좋을 것 같다고 하셨는데 운송 로봇에 쓰이는 것일까요? 각 항구당 운송 로봇은 2대, 이륜으로 생각하면 수량이 맞습니다.

넵 운송 로봇에 사용할 예정입니다. 하지만 배에 어떤 모터가 어울릴지 몰라서 배용 모터로 2개정도 추가해야 할 것 같습니다.

> 13. 가민 18650 1200mah : 리튬 폴리머 배터리로 논의해왔었는데 바뀌었네요. 혹시 이유를 들을 수 있을까요?

리튬 폴리머 가격을 확인해보니 1000mah 12개 구매시 약 50000원 정도인것을 확인했습니다. 따라서 예산인 20만원을 맞추지 못할 것 같아서 어쩔 수 없이 18650 배터리로 교체하였습니다.

> 14. 적외선 센서 모듈 : **판매처 링크**랑 **어디에 부착해 쓸 예정이신지** 설명부탁드립니다.

[판매처 링크](https://smartstore.naver.com/misoparts/products/5264231446)입니다. 운송 로봇의 자신 위치 파악용 + 정해진 길을 따라서 움직이도록 하기 위해 추가하였습니다.

> 17. 3v 소형 DC 모터 : **판매처 링크**랑 수량이 2개인데 **어디에서 & 어떤 역할로 쓸 예정이신지** 설명부탁드립니다. 아마 배일 것 같긴합니다.

넵 말씀하신대로 배용 모터입니다. 서보모터를 사용하면 혹시나 너무 느리거나 움직이지 않을까봐 추가하였습니다. [판매처링크](https://www.devicemart.co.kr/goods/view?no=12237284)

> 18. LM2596S 강하형 스텝다운 : 지금까지 회의에서 전압을 낮추는 회로를 논의한 적이 없었는데 추가한 계기가 궁금합니다.

12V 전원을 5V로 강하하여 NodeMCU등 MCU에 사용하려고 추가하였습니다. (크레인 용)

> 20. ULN2003 모터 드라이버 모듈 + 5v 스텝 모터 : 아마 모터 드라이버 모듈은 8번에서 구매하신 것 같은데 스텝 모터때문에 구매하시는건가요? (제가 제대로된 판단은 못 하겠지만) 역시 판매처 링크 알려주시면 좋을 것같습니다.

[판매처 링크](https://smartstore.naver.com/misoparts/products/5256538777)입니다. 8번은 전자석+DC모터용 모터드라이버이고, ULN2003은 스텝 모터용 드라이버입니다. 또한 견적의 가격은 5V 스텝 모터+ULM2003 드라이버를 모두 포함한 가격입니다.

> 좀 내용이 많은데 혹시 시간 되시면 조용히(부모님이 주무시고 계셔서) 줌을 하거나 아님 내일도 이슈로 토론하고 내일 저녁 8시쯤에 톡방에 올리는게 좋을 것 같습니다. 수고하셨습니다 ㅠㅠ

저는 지금 줌 회의 가능한데 성환님도 가능하시면 카톡 주시면 될 것 같습니다.

**Comment by seonghwan7694** [comment]
카톡으로 넘겨주신 엑셀 파일에 코멘트 남기고 있습니다.

**Comment by mokyabun** [comment]
넵 확인했습니다 한글파일도 수정완료하여 곧 커밋하겠습니다
