### ISSUE TITLE
크레인 모터 변경

### ISSUE THREAD

**Issue by mokyabun** [seonghwan7694/Marine_City#17]
## 문제점
크레인에 무한 회전 서보모터를 사용하면 움직임의 정확도가 떨어질 것 같습니다. 

## 해결책
대신 [스텝 모터](https://smartstore.naver.com/misoparts/products/5256538777)를 사용하면 좋을 것 같습니다.

**Comment by seonghwan7694** [comment]
네, 알겠습니다.

**Comment by seonghwan7694** [comment]
"경험적으로" 정밀하게 제어할 수 있는 모터라면 얼마든지 환영입니다

**Comment by mokyabun** [comment]
저장용 크레인에는 ESP32-CAM을 사용하는데 이 MCU에는 핀이 부족하여 스텝모터 2개, 서보모터 1개를 사용해야 할 것 같습니다.

**Comment by seonghwan7694** [comment]
확인해보겠습니다

**Comment by seonghwan7694** [comment]
모터들은 2개, 3개 정도의 여유분을 가지고 구매했다고 이해했습니다. 이슈 닫겠습니다. 수고하셨습니다.
