### ISSUE TITLE
컨테이너 보관용 크레인이 필요할 것 같습니다.

### ISSUE THREAD

**Issue by mokyabun** [seonghwan7694/Marine_City#18]
컨테이너 운송용 로봇이 운송을 하면 그 컨테이너를 들어서 보관 장소로 옮길(쌓을) 크레인이 또 필요할 것 같습니다.

**Comment by seonghwan7694** [comment]
저는 크레인이 배로부터 컨테이너를 들어서 컨테이너 운송 로봇이 받아 제 자리로 돌아가는 걸로 이해하고 있었습니다. 그러고 서는 **컨테이너 운송 로봇은 컨테이너를 내릴 필요 없이 그 상태로 있는 걸로 이해하고 있었습니다.** 하지만 말씀하신대로

> 컨테이너 운송용 로봇이 운송을 하면 그 컨테이너를 들어서 보관 장소로 옮길(쌓을) 크레인

이게 필요하다면 저희가 "크레인(배 to 로봇)"을 이미 구상했듯이 컨테이너 보관용 크레인(로봇 to 육지)은 다음과 같이 구상하면 좋을 것 같습니다.

![설계도](https://user-images.githubusercontent.com/93508637/192513152-d2e20927-f661-456a-a9b0-0b3ab6c07e06.png)
![ssss](https://user-images.githubusercontent.com/93508637/192513528-996383f6-ec11-4413-956c-2a1c9937887e.png)
1. 크레인의 작업을 마친 뒤의 초기 상태 : 바다를 봤을 때 오른쪽 구석이나 왼쪽 구석에 위치해야 한다. 다음과 같이 파란색은 크레인이 움직이는 레일이다. 빨간색은 크레인의 집게 부분이 움직일 수 있는 레일이다.

2. 컨테이너를 수송하는 로봇은 오른쪽 구석이나 왼쪽 구석에 오는 것을 목표로 한다. 컨테이너를 수송하는 로봇이 도착지점에 도달하면, 컨테이너 보관용 크레인은 지금까지 배치 안 된 곳을 계산해 컨테이너를 배치한다.


저희가 기존에 제작하려던 타워크레인은 빨간색의 범위(집게의 작동범위)가 육지부터 배가 컨테이너를 실은 곳 까지 있습니다. 따라서 컨테이너 보관용 크레인은 다음과 같이 생기면 어떨까요?


![ssss](https://user-images.githubusercontent.com/93508637/192514113-792a1255-5512-4262-a8d3-523f6e6486fe.png)

이 사진에서 노란색 물체를 주목해주세요. 제가 말한건 노란색 물체와 동일합니다. 다만 초기 위치를 정해둠으로서 소프트웨어 구현이 쉽게 하게끔... 네 그렇습니다.

**Comment by seonghwan7694** [comment]
각 항구당 1개의 _컨테이너 보관용 크레인_을 설치하는게 좋을 것 같습니다. 컨테이너 운송 로봇의 활동 범위가 (2개를 했을 때에 비해) 상대적으로 커지고 (지금 남는 예산이 얼마인지는 모르겠지만) 무엇보다 돈을 아낄 수 있기때문입니다.

**Comment by mokyabun** [comment]
넵 저도 동일하게 노란색 크레인과 같은 크레인을 생각하고 있었습니다. 2개는 너무 추가되는 부품도 많고 항구 크기도 엄청 큰게 아니라서 말씀하신대로 1개가 좋을것 같습니다.

필요한 부품 + 지금까지 부품 견적에 추가하여 #16 에 올리거나 한글 문서에 추가하겠습니다.

**Comment by mokyabun** [comment]
성환님도 동의하시고 견적에 부품 추가하여 이슈 닫습니다.
