### ISSUE TITLE
하드웨어 관련 라벨 추가

### ISSUE THREAD

**Issue by mokyabun** [seonghwan7694/Marine_City#2]
### 내용
아두이노와 같은 하드웨어를 이용하는 프로젝트다보니 하드웨어 관련 건의 라벨이 따로 있어야 할 것 같습니다.

### 원하는 라벨
🔌하드웨어

**Comment by seonghwan7694** [comment]
krome0님 의견 감사합니다. 반영하도록 하겠습니다.
