### ISSUE TITLE
하드웨어 관련 몇가지 질문사항

### ISSUE THREAD

**Issue by seonghwan7694** [seonghwan7694/Marine_City#20]
# 19, 20번 구매 내역에 관한 질문

SMPS가 교류(input)을 직류(output)으로 변환해주는 장치임을 알았습니다. AC 220V로 들어오는 전압을 DC 24V로 바꿔주는 장치이네요. 다만 궁금한 점과 몇 가지 질문 사항이 있습니다.

Q1. LRS-50-24(52W / 출력전압 : 24V / 출력전류 : 2.2A / 입력전압 : AC 85 to 264V )은 [구매처](https://www.devicemart.co.kr/goods/view?no=13231921)에 나타나있듯 재고 소진 시 납기 1달, 2달 걸릴 수 있다고 합니다. 비슷한 가격대에 비슷한 스펙을 가진 다른 제품이 없나 싶어 찾아봤는데, [링크](https://www.devicemart.co.kr/goods/view?no=12710321) (35W / 출력전압 : 24V / 출력전류 : 1.5A / 입력전압 : AC 90~264V)가 있었습니다. 비록 SMPS라는 기기를 처음봤지만, 제가 생각했을때는 배송일때문에 바꾸는게 좋지 않을까 싶습니다. krome0님은 어떻게 생각하시는지 궁금합니다. 전력 이슈때문에 그런건가요?
 
Q2. 1채널 SMPS를 구매하셨는데, 저는 채널에 대한 건 스피커 이외에 접한 적이 없어서 궁금하네요. 채널이라는게 다음과 같은 의미일까요?

![ssss](https://user-images.githubusercontent.com/93508637/192801545-b3baea49-c688-4d9a-b05a-d089579ceb95.png)

여기 사진에서는 3개는 입력으로 연결되어 있는 것 같고, 옆에 4개가 남는데, 이를 2개씩 묶어서 1채널이라고 하고 총 4개가 있으니 2채널 SMPS인가요? 저희가 사는건 5개 중 3개를 제외하니 2개가 남으니 "1채널 SMPS"다라고 생각하면 아귀가 맞는 것 같네요.

Q3. 저희는 1채널로 인가된(?) 전력을 6개의 전자석이 나눠 사용하는 것인가요?

Q4. 또 SMPS의 전원 공급 케이블로 [국산 컴퓨터 전원 파워 케이블](https://www.devicemart.co.kr/goods/view?no=12381168) 이걸 사용한다고 하셨는데 저희가 직접 저 사진처럼 피복을 벗겨내어야 하는 것인가요?

PS. 7번, 9번, 10번에서 구매하는 모듈에 어떤 회로를 구성할 지 궁금하지만 작품을 제작(회로를 구성)할 때 krome0님이 저에게 설명해주실 거라고 믿습니다. 🙏🙏🙏 (특히, 스텝다운 모듈은 크레인 1개당 1개가 필요하다고 생각했는데 3개를 구매하신다고 하셔서 조금 놀랐습니다)

# 🙏🙏🙏 이외의 궁금한 사항은 없습니다. 정말 수고하셨습니다. 🙏🙏🙏

**Comment by mokyabun** [comment]
> Q1. LRS-50-24(52W / 출력전압 : 24V / 출력전류 : 2.2A / 입력전압 : AC 85 to 264V )은 [구매처](https://www.devicemart.co.kr/goods/view?no=13231921)에 나타나있듯 재고 소진 시 납기 1달, 2달 걸릴 수 있다고 합니다. 비슷한 가격대에 비슷한 스펙을 가진 다른 제품이 없나 싶어 찾아봤는데, [링크](https://www.devicemart.co.kr/goods/view?no=12710321) (35W / 출력전압 : 24V / 출력전류 : 1.5A / 입력전압 : AC 90~264V)가 있었습니다. 비록 SMPS라는 기기를 처음봤지만, 제가 생각했을때는 배송일때문에 바꾸는게 좋지 않을까 싶습니다. krome0님은 어떻게 생각하시는지 궁금합니다. 전력 이슈때문에 그런건가요?

우선 장치들의 모든 전력 소비량을 계산해보면

- 리튬 이온 충전 모듈 5W x 4 = 20W
- 전자석 3.12W x 6 = 18.72W
- NodeMCU 0.5W x 6 = 3W
- 스텝 모터 최대 1W x 6 = 6W (크레인에 있는 스텝모터를 동시에 작동시키지 않는다고 가정)

으로 최대 약 48W 정도의 소비 전력을 가지고 있습니다. 이때, SMPS의 출력의 약 80%정도만 사용하는 것이 안전하기 때문에 52W의 SMPS를 선택했습니다. (더 높은거도 상관 없습니다.)
 
> Q2. 1채널 SMPS를 구매하셨는데, 저는 채널에 대한 건 스피커 이외에 접한 적이 없어서 궁금하네요. 채널이라는게 다음과 같은 의미일까요?
> 
> ![ssss](https://user-images.githubusercontent.com/93508637/192801545-b3baea49-c688-4d9a-b05a-d089579ceb95.png)
> 
> 여기 사진에서는 3개는 입력으로 연결되어 있는 것 같고, 옆에 4개가 남는데, 이를 2개씩 묶어서 1채널이라고 하고 총 4개가 있으니 2채널 SMPS인가요? 저희가 사는건 5개 중 3개를 제외하니 2개가 남으니 "1채널 SMPS"다라고 생각하면 아귀가 맞는 것 같네요.

SMPS 중에 5V, 24V 같이 2개의 전압을 출력해주는 SMPS가 있는데 이것을 2채널 SMPS라고 부릅니다. 저희가 쓸 SMPS는 24V 전압 1라인만 있으니 1채널 SMPS입니다.

> Q3. 저희는 1채널로 인가된(?) 전력을 6개의 전자석이 나눠 사용하는 것인가요?

네 1개의 출력에 여러 장치들을 병렬로 연결하여 나눠 사용하게 만들 예정입니다.

> Q4. 또 SMPS의 전원 공급 케이블로 [국산 컴퓨터 전원 파워 케이블](https://www.devicemart.co.kr/goods/view?no=12381168) 이걸 사용한다고 하셨는데 저희가 직접 저 사진처럼 피복을 벗겨내어야 하는 것인가요?

네 피복을 벗겨 사용해야합니다. 따로 Y타입 터미널 단자가 달린 케이블도 팔긴 했지만 가격이 일반 케이블 보다 비싸서 그냥 파워 케이블의 피복을 벗겨 사용해도 문제가 없을 것 같아서 추가했습니다.

> PS. 7번, 9번, 10번에서 구매하는 모듈에 어떤 회로를 구성할 지 궁금하지만 작품을 제작(회로를 구성)할 때 krome0님이 저에게 설명해주실 거라고 믿습니다. 🙏🙏🙏 (특히, 스텝다운 모듈은 크레인 1개당 1개가 필요하다고 생각했는데 3개를 구매하신다고 하셔서 조금 놀랐습니다)

1A는 충전 모듈이, 1A는 나머지 NodeMCU, 스텝모터가 사용한다고 치면 2A 정도이고, 충전 모듈의 최대 출력인 3A 보다 낮아서 3개만 구매해도 충분하다고 생각했습니다.

7, 9, 10를 이용한 회로는 나중에 회로 설계할때 말씀드리겠습니다.

> # 🙏🙏🙏 이외의 궁금한 사항은 없습니다. 정말 수고하셨습니다. 🙏🙏🙏

넵 성환님도 수고하셨습니다.
