### ISSUE TITLE
SRS 작성

### ISSUE THREAD

**Issue by mokyabun** [seonghwan7694/Marine_City#21]
최종 보고서는 조장님께서 초안 작성하신다고 하였고, SRS는 소프트웨어, 기술과 관련한 사항이라 저희가 작성해야 할 것 같습니다.

**Comment by seonghwan7694** [comment]
10월 17일 월요일 - 오후 3시 이후 가능
10월 18일 화요일 - APE2 끝나고 가능
10월 19일 수요일 - 창공 이후 가능 or 이산수학 끝나고 부터 창공 시작할 때까지
10월 20일 목요일 - X

17, 18, 19일 중에 줌 미팅 한번 진행할까요?

+ 저는 시험이 10월 26일에 전부 끝납니다.

**Comment by mokyabun** [comment]
줌 미팅은 19일에 진행하는게 좋을 것 같습니다. +시험은 저도 26일에 전부 끝납니다.

**Comment by seonghwan7694** [comment]
넵 이산수학 끝나고 만나요 or 줌미팅해요

**Comment by seonghwan7694** [comment]
내일 언제 괜찮으신가요?

저는
1. 이산수학 끝나고 창공 전까지
2. 줌미팅은 오후 7시부터 가능할 것 같습니다.

**Comment by mokyabun** [comment]
> 내일 언제 괜찮으신가요?
> 
> 저는
> 
> 1. 이산수학 끝나고 창공 전까지
> 2. 줌미팅은 오후 7시부터 가능할 것 같습니다.

1. 내일 이산수학 끝나고 만나서 회의 가능합니다. 
2. 줌 회의는 회의해야할 사항이 남아있으면 7시부터 진행하는거로 하면 될 것 같습니다.

**Comment by seonghwan7694** [comment]
[SRS 보고서 작성을 위한 공유문서 링크](https://docs.google.com/document/d/12SKhiQOtXhMc8KIIMcNGDDNT1EK8Jtnk/edit?usp=sharing&ouid=104670682463251515675&rtpof=true&sd=true)

**Comment by seonghwan7694** [comment]
1.1 SRS 목적
1.3 개발 범위
2.1 프로젝트의 개요
2.4 소프트웨어 운영 환경

**Comment by seonghwan7694** [comment]
![image](https://user-images.githubusercontent.com/93508637/196604509-4f113ad2-12a1-47d8-a746-54cfcb04142c.png)

**Comment by seonghwan7694** [comment]
#23 로 이관하겠습니다 수고하셨습니다 👍🏻
