### ISSUE TITLE
[SRS 보고서 작성을 위한 공유문서 링크]

### ISSUE THREAD

**Issue by seonghwan7694** [seonghwan7694/Marine_City#23]
[SRS 보고서 작성을 위한 공유문서 링크](https://docs.google.com/document/d/12SKhiQOtXhMc8KIIMcNGDDNT1EK8Jtnk/edit?usp=sharing&ouid=104670682463251515675&rtpof=true&sd=true)

**Comment by seonghwan7694** [comment]
@krome0 몸살 감기는 나아지셨나요. 다름이 아니라, 의논 할/해야할 사항이 몇 있어 이슈로 남깁니다.

> 1. 웹 서버를 열 언어로 파이썬을 사용한다고 적혀져있는데 Django 프레임워크를 사용할 계획인가요?
>> 물어보는 이유는 프레임워크인지라 스케줄의 여유가 있을 때 조금이라도 이해해보려고 합니다. 12.08 (목) ~ 12.14 (수)가 기말고사라니.. 시간이 촉박하긴하네요.
> 2. 도커 얘기가 잠깐 나왔던 것 같은데, 사용할 계획인가요?
>> 물어보는 이유는 위의 것과 같습니다. 스케줄의 여유가 있을 때 이해해보려고요.
>> 도커를 안 쓴다면, 파이썬 가상환경을 민형님이 세팅하셔서 저장소에 커밋하시면 될 것 같습니다. (도커를 대체하는 방법이 맞나요..? 블로그 글만 읽어서 잘 모르겠네요...)
> 3. 역할 분담을 하지 않아서 이르지만 잠깐 얘기해보겠습니다. 예전 회의에서... 이런 부분(사진 참고)이 있긴 한데요. 단순하게 생각하면 웹 서버는 민형님이 웹 클라이언트는 제가 맡으면 될 것 같습니다.
> ![image](https://user-images.githubusercontent.com/93508637/198891848-51f807ca-a849-4b07-89dd-5057e89342bc.png)
> 4. 도커 + 장고 + 바닐라 JS 조합으로 가는것 일까요?
>> 저희가 UI/UX(용어가 맞나...?)를 한번도 의논한 적이 없어서요. 풀어서 말하자면, "사용자는 항구를 간단하게 관리할 수 있게 된다"라는 것에 대해 "어떻게 간단하게 관리할 수 있게 할건데?"라는 질문에 대한 논의가 아예 이루어지지 않았습니다.
>> 도커 + 장고 + 리액트 + (CSS 프레임워크) 조합이 정말 결과물적으로는 이상적일 것 같습니다만.. 여러가지 이유(시간적 + 능력적 이유)로 고민이 되네요...
>5. 어쨌든 프로젝트를 끝내기 위해서는 하드웨어를 빠르게 완성(3D 프린터기 이용)하는게 가장 중요할 것 같습니다. SRS보고서는 제가 마무리 지어보겠습니다.

**Comment by seonghwan7694** [comment]
민형님은 제가 쓴 SRS 보고서 체크해주시고 위에 댓글도 체크해주시고 3.2 하드웨어 인터페이스 작성해주시면 될 것 같습니다.

**Comment by mokyabun** [comment]
> 1. 웹 서버를 열 언어로 파이썬을 사용한다고 적혀져있는데 Django 프레임워크를 사용할 계획인가요?

사용해본 웹 백엔드 프레임워크가 없어서 찾아보니까 Fastapi, Django가 있는거 같은데 일단 Django를 사용해서 제작하는 것이 좋아보입니다. (Django가 더욱 유명해서 단기간에 학습하고 제작하기에 자료가 더욱 많을 것 같습니다.)

> 2. 도커 얘기가 잠깐 나왔던 것 같은데, 사용할 계획인가요?
> 물어보는 이유는 위의 것과 같습니다. 스케줄의 여유가 있을 때 이해해보려고요.
> 도커를 안 쓴다면, 파이썬 가상환경을 민형님이 세팅하셔서 저장소에 커밋하시면 될 것 같습니다. (도커를 대체하는 방법이 맞나요..? 블로그 글만 읽어서 잘 모르겠네요...)

도커는 사용해야할지 아직 잘 모르겠습니다 웹 서버를 만들어본적이 없어서 그냥 노트북에서 네이티브 환경에서 돌리는게 나을지 아니면 도커 환경에서 돌리는게 나을지 아직 확신이 안가네요, 파이썬 의존성 관리는 poetry 같은걸 사용하면 될 것 같습니다.
 
> 3. 역할 분담을 하지 않아서 이르지만 잠깐 얘기해보겠습니다. 예전 회의에서... 이런 부분(사진 참고)이 있긴 한데요. 단순하게 생각하면 웹 서버는 민형님이 웹 클라이언트는 제가 맡으면 될 것 같습니다.
>    ![image](https://user-images.githubusercontent.com/93508637/198891848-51f807ca-a849-4b07-89dd-5057e89342bc.png)

넵 JS 같은 웹 클라이언트를 프로그래밍하는 언어는 제가 사용해본적이 없어서 그렇게 해주시면 좋을 것 같습니다. 저도 최대한 공부해보도록 하겠습니다.

> 4. 도커 + 장고 + 바닐라 JS 조합으로 가는것 일까요?
> 
> 저희가 UI/UX(용어가 맞나...?)를 한번도 의논한 적이 없어서요. 풀어서 말하자면, "사용자는 항구를 간단하게 관리할 수 있게 된다"라는 것에 대해 "어떻게 간단하게 관리할 수 있게 할건데?"라는 질문에 대한 논의가 아예 이루어지지 않았습니다.
> 도커 + 장고 + 리액트 + (CSS 프레임워크) 조합이 정말 결과물적으로는 이상적일 것 같습니다만.. 여러가지 이유(시간적 + 능력적 이유)로 고민이 되네요...

우선 웹 백엔드 프레임워크는 장고를 사용하는게 좋을 것 같고 프론트는 어떤게 좋을지 저도 잘 모르겠습니다. 그리고 UI/UX 디자인은 각자 어떤식으로 제작을 할지 디자인해서 설명이랑 같이 #24 이슈에 올려보면 좋을 것 같습니다.

> 5. 어쨌든 프로젝트를 끝내기 위해서는 하드웨어를 빠르게 완성(3D 프린터기 이용)하는게 가장 중요할 것 같습니다. SRS보고서는 제가 마무리 지어보겠습니다.

SRS는 제가 금요일부터 아파서 잠만 자느라 거의 손을 못댔는데 매우 잘 써주셨더라고요 죄송하고 감사합니다..

**Comment by seonghwan7694** [comment]
~~조장님이 올린 것과 통합해서 커밋해두겠습니다.~~

통합 안 합니다
