### ISSUE TITLE
UI/UX 디자인

### ISSUE THREAD

**Issue by mokyabun** [seonghwan7694/Marine_City#24]
UI/UX 디자인을 결정해야합니다.

**Comment by seonghwan7694** [comment]
![request_response_lifecycle_Django.png](https://user-images.githubusercontent.com/93508637/198954748-9c58225a-93cb-4571-9349-9c50805e2f21.png)
장고가 프레임워크인지라 위 다이어그램처럼 장고 동작방식을 기반으로 한 UI/UX의 Flow Chart/명세서를 화요일 오후 or 새벽 중으로 구성하여 여기 이슈에 남기겠습니다.

내일까지 다음을 학습해오겠습니다.

> 1. HTTP 프로토콜
> 2. 장고 프레임워크 플로우(디렉터리 구조, 파일의 역할)
> 3. "장고가 웹 서버로서 역할을 할 수 있는지?"에 관한 답.. 검색해봤는데요. 장고는 웹 서버로서 역할을 할 수 있는지 모르겠어서요. 저번주 토요일에 장고를 맛만 봐봤는데요. 작업환경 구성하고 python manage.py runserver 치니까 로컬 서버가 열리긴하던데.. 위 다이어그램을 보면 Nginx 나 aphache가 필요하다고 하는것 같아서요. 희미하긴하지만, 위 사진에서 테두리 부분이 초록색인게 있는데 그 부분을 장고가 다루는 영역임을 나타내는 것 같습니다.

UI/UX와 기술적으로 가능한지에 대한 여부는 제가 최대한 확인하고 결정해보겠습니다. 나중에 줌 회의해요. 아프시다면 무리하지마시고 푹 쉬세요 👍🏻

**Comment by seonghwan7694** [comment]
- 마친 것 : 기술적 사항을 검토 -> 장고 플로우 차트 완성 -> SRS 보고서에 넣음
- 해야할 것 : 장고 + 리액트 + 부트스트랩 시도 -> UX/UI 결정 -> SRS 보고서에 넣기

**Comment by seonghwan7694** [comment]
수요일날 공개문서에 적힌 핑크색 내용(UI/UX, 장고 활용 방안 등) 전면 수정하겠습니다.

**Comment by seonghwan7694** [comment]
아까 설명한 UI로 가겠습니다.
