### ISSUE TITLE
[웹서버 관련 이슈]

### ISSUE THREAD

**Issue by seonghwan7694** [seonghwan7694/Marine_City#25]
> 1. APACHE + mod_wsgi + django 를 선택하겠습니다. 괜찮나요?
> 1.1 저는 WSGI의 종류 중 하나인 gunicorn으로 하려고 했지만, gunicorn은 윈도우 시스템에서 돌아가지 않음을 확인했습니다. [증거1](https://stackoverflow.com/questions/11087682/does-gunicorn-run-on-windows), [증거2](https://gunicorn.org/) uWSGI도 마찬가지였습니다. gunicorm, uWSGI 모두 unix-like인 것 같습니다. 그나마 mod_wsgi는 윈도우 운영체제에서도 [비공식적으로](https://www.opentutorials.org/module/3923/25080) 호환 가능한 것 같습니다.

> 2. windows 10 기반의 apache2.4로 서버를 열고 cmd에서 ipconfig로 ipv4주소를 확인한 후, 스마트폰에서 그 ipv4주소를 입력했는데요. (당연하지만) 연결에는 성공했습니다. 이제 Apache 웹 서버에 django 프로젝트를 연동시켜줄려고 했습니다. 하지만, 다음과 같은 문제 상황이 발생했습니다. windows powershell에서 poetry의 설치는 성공했으나, poetry --version 명령어등을 인식하지 못합니다. 환경변수 문제일것같아서 몇 시간동안 시도했는데요. 계속 잡아줘도 안 되네요.. 😭😭😭 아래 사진은 제 오류 로그입니다.

![image](https://user-images.githubusercontent.com/93508637/199241387-d7f704c0-b4f2-4320-8e00-36720642746b.png)

> 3. apache + mod_wsgi + django 조합 또는 nginx + gunicorn + django 조합으로 보통 제작하는 것 같습니다.

> 4. 저는 window powershell 말고도 wsl2가 있어서 그걸로 시도해보니 poetry shell 과 같은 명령어가 잘 먹혀서 poetry 좀 만지작 거리다가 다이어그램도 그려놓았습니다. 똑같이 환경변수 설정하는 과정이 [문서](https://python-poetry.org/docs/#installation)에 존재하는데 wsl2에서는 성공했고 powershell에서는 계속해도 안되는데 정말 미치겠네요 ㅋㅋㅋㅋㅋ
![image](https://user-images.githubusercontent.com/93508637/199251631-1c63162a-2f59-4521-9a44-bd756548a66d.png)

제가 생각했을 때, 남은 선택지는 5가지 정도인 것 같습니다.. ㅜㅜ

1. 윈도우 10기반 power shell에서 poetry와 mod_wsgi 설치를 성공한다. APACHE + mod_wsgi + django 조합으로 웹 서버를 구축하고 성공한다.
2. 웹 서버는 ubuntu 18.04나 20.04로 '로컬에서' vmware, virtualbox를 통해 연다.
3. 도커를 사용한다.
4. AWS과 같은 클라우드 컴퓨팅 서비스를 이용한다.
5. Unix-like한 민형님의 맥북으로 웹 서버를 구축한다... ㅋㅋㅋㅋ

어떤게 괜찮아 보이시나요? 저는 2번이 그나마 ... 괜찮다고 생각합니다.

\+ 계속 구글링해봤는데 ubuntu 랑 centOS쪽 자료가 확실히 많은 것 같습니다...
\+ 3번, 4번은 피하고 싶습니다 ㅠ

그럼 20000 😭😭😭 Django 프레임워크 공부 + UX/UI 고르러 가겠습니다...

**Comment by mokyabun** [comment]
오늘 저녁까지 제 서버, 맥에서 테스트해보고 답변드리겠습니다

**Comment by seonghwan7694** [comment]
저는 듀얼 OS로 우분투로 시도해보겠습니다.

**Comment by mokyabun** [comment]
<img width="679" alt="스크린샷 2022-11-02 오후 11 23 18" src="https://user-images.githubusercontent.com/37375701/199517867-65183ec1-ca67-4d1e-99fd-ba39de796271.png">

맥에서는 gunicorn도 작동하고 nginx도 잘 작동하는것 같네요

**Comment by seonghwan7694** [comment]
감사합니다... 감사합니다.. 그러면 민형님 맥북에서 웹 어플리케이션 서버 돌리는걸로 할까요??

```
📦 Marine_City
├─ documents
├─ images
├─ source_code
└─ [장고 프로젝트 이름]
   ├─ [웹 사이트 이름]
   ├─ poetry.lock
   ├─ pyproject.homl
   └─ manage.py
```
©generated by [Project Tree Generator](https://woochanleee.github.io/project-tree-generator)

장고 웹사이트 제작을 시작하기위해 민형님이 커밋해주시면 정말 좋을 것 같습니다! 

잘 아시겠지만 이렇게 하는게 맞을까요? 커밋 부탁드리겠습니다 🙏🙏🙏

> mkdir [장고 프로젝트 이름]
> cd [장고 프로젝트 이름]
> poetry init
> poetry shell
> poetry add django gunicorn
> django-admin [웹사이트 이름] . 

. 을 추가해야지 디렉터리 안에 디렉터리가 안 생기더라고요..! 웹 서버 배포 성공해주셔서 정말 감사합니다.

/+ 저는 앞으로 우분투에서 작업하게 될 것 같습니다.

**Comment by seonghwan7694** [comment]
조장님이 결정하는 부분도 있으니 그냥 STAY도 괜찮아 보입니다. 오늘 수고하셨습니다.

**Comment by mokyabun** [comment]
넵 우선 월요일에 만나서 구체적으로 어떻게 할지 정하고 시작해도 될 것 같습니다. 그때까지는 서로 Django나 프론트같은 부분을 좀 더 공부해보면 좋을 것 같습니다. 성환님도 수고하셨습니다.

**Comment by seonghwan7694** [comment]
동의합니다

**Comment by seonghwan7694** [comment]
우분투를 사용하면서 제 이슈는 없어졌으니 이슈를 #27로 이관하고 닫겠습니다.
