### ISSUE TITLE
아두이노(MCU) 선정

### ISSUE THREAD

**Issue by mokyabun** [seonghwan7694/Marine_City#3]
## 내용
어떤 아두이노(MCU)를 사용할 것인지 정해야 합니다.

**Comment by mokyabun** [comment]
아두이노를 WIFI를 사용하여 중앙서버에서 제어할거면 LOLIN D1 MINI (https://www.devicemart.co.kr/goods/view?no=1327519)나 NodeMCU (https://www.devicemart.co.kr/goods/view?no=1322088)를 사용하는 것이 좋을것 같습니다.

**Comment by seonghwan7694** [comment]
먼저, 의견 감사합니다.

이슈는 일찍 읽었는데, "아두이노를 WIFI를 사용하여 중앙서버에서 제어"라는 프로세스 이해하지 못하고 궁금하기도 해서 구글링(https://shortest.link/4zsg)을 좀 하다 왔습니다. 급하게 한국어 문서를 찾아봤지만, IoT는 유명한 분야니 그만큼 영어로 검색하면 소스가 넘칠 것 같습니다.

저번에 krome()님께서 말해주신 아두이노 프로 미니(https://www.devicemart.co.kr/goods/view?no=1289321)를 생각하면서 "크레인, 배, 물류 시스템" 등등에 대한 제어를 '아두이노 프로 미니'로 "타이밍을 잘 맞춰" 제어해야겠구나 싶었습니다.
 
> 지금 의견을 들으니 이것이 떠오릅니다. 물체를 A 에서 B 로 옮기는 '타워크레인'이 B에 도착했다라는 신호(딜레이와 모터 파워로 실험적으로 계산)를 LOLIN D1 MINI나 NodeMCU(이하 loT MCU라고 칭하겠음)에 보내면  IoT MCU가 웹 서버에 보내고, 웹 서버는 다음 프로세스(예를들자면, '배를 출발시킨다')를 진행시키기 위해 다음 프로세스를 담당하는 아두이노 보드에 신호를 전달한다.

저는 위와 같이 이해했습니다. 제가 이해한 게 맞는지 궁금하네요 :)

### 다음과 같은 이유로 IoT가 가능한 보드들을 긍정적으로 검토하겠습니다.
1. loT는 유명한 분야이니 그만큼 영어로 검색하면 소스가 넘친다.

2. IoT MCU를 통해 중앙집중적으로(=정해진 절차에따라) 프로세스가 진행되므로, 작품의 '정상적인 작동'에 대한 신뢰성이 올라간다.

감사합니다.

**Comment by mokyabun** [comment]
넵 여러 기기들이 상호작용해야하는 프로젝트라서 중앙서버를 두고 여러 MCU를 컨트롤하는 방식으로 작동하는 것이 좋아보입니다.

중앙서버로는 라즈베리파이 3 정도를 사용하면 될 것 같습니다.
- https://www.devicemart.co.kr/goods/view?no=12379851 (3 A+ 35900원)
- https://www.devicemart.co.kr/goods/view?no=1377518 (3 B+ 49000원)

**Comment by seonghwan7694** [comment]
아하 중앙서버로 RBP 3로 두고 리프 노드들을 MCU로 하자는 이야기로 이해했습니다.

RBP 4에 비해 RBP 3은 저렴하네요. 좋을 것 같습니다.

**Comment by seonghwan7694** [comment]
LOLIN D1 -> NodeMCU

**Comment by seonghwan7694** [comment]
우선순위 1번 : LOLIN D1
우선순위 2번 : NodeMCU

즉, 작품의 크기 이슈때문에(작은 것일 수록 작품 제작에 유리함) LOLIN D1을 활용하는 방안으로 선택하고 이슈 닫겠습니다. 수고하셨습니다.
