### ISSUE TITLE
마지막 이슈

### ISSUE THREAD

**Issue by seonghwan7694** [seonghwan7694/Marine_City#30]
혹시나해서 말해드리는데 리액트 공부하겠다는 말 Joke입니다 ㅠㅜ 시험공부를 안 해가지구.. 도안 열심히 제작하셨는데 엎어져서 아쉬웠고 남은 3주일동안 빠이팅해봅시다!

민형님이 해주시면 좋을 것 같은건

1. 하드웨어 관계 잡아주기
-> 제가 이해한 바로는 다음과 같습니다. 키오스크(=노트북)에 연결된 esp8266으로 마우스를 제어한다. 장애인은 esp8266과 스위치로 제작된 디바이스를 가지고 있고, 장애인이 가지고 있는 esp8266과 키오스크에 연결된 esp266은 espnow 통신을 사용한다. 몇 개의 esp8266를 사용할 것이며 각각의 용도는 무엇인지, 그리고 사용하는 프로토콜 정도만 명확하면 좋을 것 같네요!

2. 웹 인터페이스
-> 아까 시중에 있는 키오스크를 벤치마킹하시겠다고 했는데,저랑 민형님이 동시에 개발할 것이기 때문에 논의가 필요하고, 시간 들여 구현만 하면 되니까 같이 의논하며 레이아웃을 잡고 구현도 동시에 나눠서 하는 방향으로 진행하면 좋을것같습니다.

3. 추가적인 기능
-> 아까 도난방지기능같은거 말씀해주신걸 말합니다! 위치기반 도난방지기능은 자바스크립트( https://7942yongdae.tistory.com/150 ) 로 구현히 가능해보입니다.

새 레포를 열어 작업하는게 좋아보이고(기존 레포는 기록 보존을 위해 삭제하지 않을 예정입니다) 민형님이 새 레포 생성해주시면 좋겠습니다.

@krome0 수고하셨습니다.

**Comment by mokyabun** [comment]
새 레포 만들었습니다. https://github.com/krome0/universial-kiosk

우선 docs/how-it-works-kr.md에 간단하게 어떻게 제작할 예정인지 적어봤습니다.
