### ISSUE TITLE
커밋 기록을 통한 학번 이메일 확인 가능성

### ISSUE THREAD

**Issue by mokyabun** [seonghwan7694/Marine_City#4]
## 내용
커밋 기록에서 학번, 이메일 확인이 가능합니다. 
지금까지 커밋 기록이 README.md 파일 수정밖에 없어서 커밋 기록을 초기화 하는 것이 좋을 것 같습니다.

## 해결 방법
커밋 내역 초기화

**Comment by seonghwan7694** [comment]
넵 오후 8시 넘어서 초기화하도록 하겠습니다

**Comment by seonghwan7694** [comment]
작업 완료했습니다.
