### ISSUE TITLE
[중요] 제작해야할 것 & 필요한 재료

### ISSUE THREAD

**Issue by seonghwan7694** [seonghwan7694/Marine_City#5]
지금 생각나는거 다 적어보겠습니다.

우리 작품의 컨셉 : IoT로 구현한 해양 물류 시스템(컨셉은 변동 가능)

0. [맵](https://mblogthumb-phinf.pstatic.net/MjAyMTA5MDJfMjg1/MDAxNjMwNTYyMTY5MDkz.RpneNBgAan4A9AXbGd5T-iD_Vw8gDBE4JofDQ06RusYg.prJZtxUokmHvumnvNVv38zIVUWWG8gAHFjmzODQs4n8g.JPEG.talminam/20210829_105018.jpg?type=w800) : 아크릴(확정) 2T

1. [타워 크레인](https://sc04.alicdn.com/kf/H2bb17d21e38b4ecea57d267ab070feea4.jpg)
> [필요한 재료]
>
> [NodeMCU](https://www.devicemart.co.kr/goods/view?no=1322088)
>
> [아크릴 판](https://smartstore.naver.com/sellacrylic/products/5762492997?NaPm=ct%3Dl8h6v0zc%7Cci%3Dabadccf8d932a93d98ef9b4283bded93870ea7a1%7Ctr%3Dsls%7Csn%3D3736569%7Chk%3Dffc10abb69c32278c4f54c1f851b38e32a495d61) 5T 미만(5T 이상은 아크릴 칼로 자르기 어렵다고 함) or [포맥스](https://smartstore.naver.com/acrylmall/products/368871146?NaPm=ct%3Dl8h7ua9s%7Cci%3Df00ae5a596a40cb9db8435308df3a3c9f91d8b8e%7Ctr%3Dslsl%7Csn%3D157201%7Chk%3D24a5cc895b6750c8271040e068be5d84cf3e1a6e)
>
> [아크릴 커터기](https://www.coupang.com/vp/products/5151436770?itemId=7079046447&vendorItemId=74371048887&q=%EC%95%84%ED%81%AC%EB%A6%B4+%EC%BB%A4%ED%84%B0&itemsCount=36&searchId=ebfb84830ea2423a97110d745b74b375&rank=2&isAddedCart=)
>
> 도색 : [락카](https://www.coupang.com/vp/products/4706737?itemId=21425405&vendorItemId=70719944108&q=%EB%9D%BD%EC%B9%B4&itemsCount=36&searchId=9b05c77f3be64d0e9c782a3fa98cdb36&rank=2&isAddedCart=) or 물감
>
> [아크릴 접착제](https://www.coupang.com/vp/products/56463843?itemId=195366114&vendorItemId=83215548890&q=%EC%95%84%ED%81%AC%EB%A6%B4+%EC%A0%91%EC%B0%A9%EC%A0%9C&itemsCount=36&searchId=0056c4b76eb44e41b627e5478392f1ae&rank=1&isAddedCart=) or [순간 접착제](https://www.coupang.com/vp/products/5471126398?itemId=8407252881&vendorItemId=75694905408&q=%EC%88%9C%EA%B0%84%EC%A0%91%EC%B0%A9%EC%A0%9C&itemsCount=36&searchId=14c606d492094f6f9d0f7881438680be&rank=3&isAddedCart=)
>
> [전자석 모듈](https://www.devicemart.co.kr/goods/view?no=1382905) : 이외의 전자석 모듈은 작동전압이 DC 12V로 높은 편 -> 다른 회로가 추가로 요구됨.
>
> [모터](https://www.devicemart.co.kr/goods/view?no=12237285) : 3개 필요

2. [화물](http://thumbnail.10x10.co.kr/webimage/image/basic600/267/B002677878.jpg?cmd=thumb&w=400&h=400&fit=true&ws=false)
> [필요한 재료]
>
> [아크릴 판](https://smartstore.naver.com/sellacrylic/products/5762492997?NaPm=ct%3Dl8h6v0zc%7Cci%3Dabadccf8d932a93d98ef9b4283bded93870ea7a1%7Ctr%3Dsls%7Csn%3D3736569%7Chk%3Dffc10abb69c32278c4f54c1f851b38e32a495d61) 5T 미만(5T 이상은 아크릴 칼로 자르기 어렵다고 함) or [포맥스](https://smartstore.naver.com/acrylmall/products/368871146?NaPm=ct%3Dl8h7ua9s%7Cci%3Df00ae5a596a40cb9db8435308df3a3c9f91d8b8e%7Ctr%3Dslsl%7Csn%3D157201%7Chk%3D24a5cc895b6750c8271040e068be5d84cf3e1a6e)
> 
> [순간 접착제](https://www.coupang.com/vp/products/5471126398?)
>
> 도색 : [락카](https://www.coupang.com/vp/products/4706737?itemId=21425405&vendorItemId=70719944108&q=%EB%9D%BD%EC%B9%B4&itemsCount=36&searchId=9b05c77f3be64d0e9c782a3fa98cdb36&rank=2&isAddedCart=) or 물감
>
> [아크릴 커터기](https://www.coupang.com/vp/products/5151436770?itemId=7079046447&vendorItemId=74371048887&q=%EC%95%84%ED%81%AC%EB%A6%B4+%EC%BB%A4%ED%84%B0&itemsCount=36&searchId=ebfb84830ea2423a97110d745b74b375&rank=2&isAddedCart=)
> 100원 동전 : 타워 크레인의 전자석 모듈에 달라 붙기 위해서 씀

3. 라즈베리파이 : MCU들을 중앙에서 제어하는 역할을 함
> 있으면 좋겠지만, 재고가 없고... [비싸서](https://smartstore.naver.com/keytronic/products/7077048559?NaPm=ct%3Dl8h8vfgo%7Cci%3D0EDQ0e1jc31xAlE38LkR%7Ctr%3Dpla%7Chk%3D2af1aad6bb087244cb89bb144981c07067ef2656) 아마 노트북으로 대체되지 않을까... 싶음

**Comment by mokyabun** [comment]
배는 3D프린팅이나 스티로폼으로 만들면 될 것 같습니다

**Comment by seonghwan7694** [comment]
네. 맵을 제외한(맵은 아크릴로 제작하기로 합의한걸로 알고있습니다) 모든 구조물은 3D 프린팅을 우선시하되, 안되면 포맥스나 배의 경우 스티로폼으로 만드는걸로 알고 있겠습니다.

3D 프린터로 만들게 되면 여러가지 부속용품이 필요없어서(도색 용품, 접착제, 아크릴판) 비용적인 부분에서 이득을 얻을 수 있을 것 같습니다.
