### ISSUE TITLE
라즈베리파이 선정

### ISSUE THREAD

**Issue by seonghwan7694** [seonghwan7694/Marine_City#7]
더 좋은 가격이 있다면 수정 부탁드립니다.

[라즈베리파이4 B (Raspberry Pi 4 Model B) 1GB + 방열판](https://www.devicemart.co.kr/goods/view?no=14574087) - 60,000원

[라즈베리파이4 (Raspberry Pi 4 Model B) 2GB + 방열판](https://www.devicemart.co.kr/goods/view?no=12234533) - 80,000원

**Comment by mokyabun** [comment]
> 재료비 지원 가능 사이트:  샘플전자, 에듀이노, 네이버 스마트스토어
> - 반드시 위 사이트 내에서 부품을 찾아 신청서를 작성해주세요.

https://canvas.ssu.ac.kr/courses/17470/discussion_topics/63275

공지에 이런 사항이 있어서 다른 사이트에서 구매가 가능한지 모르겠습니다. 저기 사이트내의 가장 저렴한 보드는 어제 회의 중에 확인했던 http://www.robot.co.kr/product/detail.html?product_no=2915&cate_no=80&display_group=1 이거 인것 같습니다.

**Comment by mokyabun** [comment]
라즈베리파이와 비슷한 보드중에 [Orange PI](https://m.smartstore.naver.com/makeitfun/products/6400452721?NaPm=ct%3Dl8i18cjs%7Cci%3D3343aeb219fcad5bc01bc6a14809d979d50a3235%7Ctr%3Dslsl%7Csn%3D361723%7Chk%3D6f0bf8d632ecf36889dda44a1036e84b05a701b6)라는 보드도 있는것 같습니다. 네이버 스토어 기준 52800원이지만 사양이나, 호환성 같은 부분은 조사가 더 필요할 것 같습니다

**Comment by mokyabun** [comment]
하드커널사의 [ODROID](https://www.hardkernel.com/ko/) 제품들도 가격은 저렴해보이는데 호환성, 성능을 조사해봐야 할 것 같습니다

**Comment by mokyabun** [comment]
> 하드커널사의 [ODROID](https://www.hardkernel.com/ko/) 제품들도 가격은 저렴해보이는데 호환성, 성능을 조사해봐야 할 것 같습니다

ODRIOD는 우분투 22.04버전 설치가 가능한 것으로 보입니다. [링크](https://wiki.odroid.com/getting_started/os_installation_guide#tab__odroid-xu4)

**Comment by seonghwan7694** [comment]
1. 오늘 '디바이스 마켓'이 가능한지 물어봐야 겠습니다.

제가 임시로 [제품 명세서를 작성](https://github.com/seonghwan7694/Marine_City/tree/master/documents)하였는데, 확실히 디바이스 마켓이 종류가 많습니다. 로린 D1만 봐도, [에듀이노](https://www.eduino.kr/product/search.html?view_type=&supplier_code=&category_no=0&search_type=product_name&keyword=D1&product_price1=&product_price2=&order_by=&x=0&y=0)는 관련 제품이 1개밖에 없는 반면 [디바이스 마켓](https://www.devicemart.co.kr/goods/search?keyword_log_flag=Y&search_text=LOLIN+D1&q=LOLIN+D1&if_count_chk=&stock=&x=0&y=0)은 2개 정도 있습니다. 또한, 디바이스 마켓이 라즈베리파이 [정식 수입처](https://www.raspberrypi.com/products/raspberry-pi-4-model-b/)라니 가능하면 디바이스 마켓을 이용하는게 좋다고 생각합니다.

+ 어제 확인했던 [샘플전자](https://www.robot.co.kr/product/detail.html?product_no=2915&cate_no=80&display_group=1)의 라즈베리파이는 **자체제작**인데다 세부 스펙(램이 몇 기가인지)를 알려 주지 않아서 개인적으로 신뢰성이 가지 않습니다.

2. GUI버전 우분투를 쓰기 위해서는 램이 적어도 4GB정도는 확보되어야 한다고 생각하는데 어떻게 생각하시는지요. 4GB라고 말한 이유는 다음과 같습니다. 이전에 버츄얼 박스에서 리눅스를 올렸을 때 추천하는 램 용량이 4GB로 기억하기 때문입니다. 결론적으로... 우분투 OS의 RAM USAGE에 따라 결정하는 게 좋을 것 같습니다.

+ 여기 [링크](https://www.youtube.com/watch?v=NtX1z1kfQ9w)보시면 우분투 OS의 RAM USAGE 는 700MB인 것 같습니다.

+ 말씀해주신 Orange PI보다는 하드커널사의 [ODROID](https://www.hardkernel.com/ko/)가 더 제 마음에 듭니다. M.2 슬롯부터 하드웨어에 신경쓴 느낌이 든다는 느낌을 들어서일까요..? 개인적인 느낌입니다 하 하

3. ODRIOD 사의 제품을 말씀해주셨는데 저는 괜찮은 것 같습니다. 라즈베리파이에 비교해 램성비가 좋은 것 같기 때문입니다.

4. 라즈베리파이를 선택하든, ODRIOD 사의 제품을 선택하든, micro SD카드를 구매해야하는데(ODRIOD의 제품은 M.2 슬롯을 제공하는 게 인상적이긴합니다) 64GB 정도면 적당하겠죠?

5. 오늘 수업시간에 교내에 사용가능한 3D 프린터기가 있는지 물어보면 좋을 것 같습니다.

**Comment by mokyabun** [comment]
> 1. 오늘 '디바이스 마켓'이 가능한지 물어봐야 겠습니다.

확실히 디바이스마트에 다양한 상품이 있어서 물어봐주시면 감사하겠습니다.

> 2. GUI버전 우분투를 쓰기 위해서는 램이 적어도 4GB정도는 확보되어야 한다고 생각하는데 어떻게 생각하시는지요. 4GB라고 말한 이유는 다음과 같습니다. 이전에 버츄얼 박스에서 리눅스를 올렸을 때 추천하는 램 용량이 4GB로 기억하기 때문입니다. 결론적으로... 우분투 OS의 RAM USAGE에 따라 결정하는 게 좋을 것 같습니다.

Ubuntu Minimal 같은 경우에는 CLI환경 밖에 지원하지 않지만(GUI는 따로 설치 가능) 도커에서 구동해본 결과 램을 500MB이하로 사용하는것 같았습니다. 또한 저희는 서버가 단순히 아두이노 제어만 하면 돼서 굳이 GUI버전 Desktop용 우분투를 설치할 이유가 없을것 같습니다.

> + 말씀해주신 Orange PI보다는 하드커널사의 [ODROID](https://www.hardkernel.com/ko/)가 더 제 마음에 듭니다. M.2 슬롯부터 하드웨어에 신경쓴 느낌이 든다는 느낌을 들어서일까요..? 개인적인 느낌입니다 하 하
> 3. ODRIOD 사의 제품을 말씀해주셨는데 저는 괜찮은 것 같습니다. 라즈베리파이에 비교해 램성비가 좋은 것 같기 때문입니다.

네 저도 동의합니다 가능하면 ODROID의 SBC를 사용하는것이 좋을것 같습니다. 하지만 ODROID의 구매처가 [공식홈페이지](https://www.hardkernel.com/ko/) 밖에 없어서 이것도 디바이스마트와 함께 문의를 해주시면 좋을 것 같습니다.

> 4. 라즈베리파이를 선택하든, ODRIOD 사의 제품을 선택하든, micro SD카드를 구매해야하는데(ODRIOD의 제품은 M.2 슬롯을 제공하는 게 인상적이긴합니다) 64GB 정도면 적당하겠죠?

Ubuntu Minimal/Server/Core 모두 1GB 미만의 용량을 가지고 있어서 Ubuntu Desktop을 사용할 것이 아니면 SD카드는 8GB이상이면 될 것 같습니다.

> 5. 오늘 수업시간에 교내에 사용가능한 3D 프린터기가 있는지 물어보면 좋을 것 같습니다.

오늘 수업시간이 사전녹화 수업이라 메일로 문의하거나 수요일 수업에 여쭤봐야할 것 같습니다.

**Comment by seonghwan7694** [comment]
```c
저희 조는 "IoT 해양 운송/물류 시스템"을 구축하려고 합니다. 따라서, 중앙 서버(라즈베리파이 or ODROID)로 LOLIN D1을 제어하려고 합니다.

<부품 주문서 관련 질문>
디바이스 마켓 이용 가능한지 궁금합니다.
저희 조가 구매하려는 것은 다음과 같습니다.

1. 전자석 모듈 : https://www.devicemart.co.kr/goods/view?no=1382905
2. 라즈베리파이 : https://www.devicemart.co.kr/goods/view?no=14574087
3. LOLIN D1 : https://www.devicemart.co.kr/goods/view?no=1327519

Q1. 가격이 합리적이고 저희 조가 필요로하는 제품도 판매하는 '디바이스마트'의 제품을 부품주문서에 넣어도 되는지 궁금합니다.

Q2. 라즈베리파이를 대체하여 하드커널사의 ODROID(https://www.hardkernel.com/shop/odroid-m1-with-4gbyte-ram/)을 부품 주문서에 넣어도 되는지 궁금합니다.

<3D 프린터 이용 질문>

Q3. 저희 조가 해양 운송/물류 시스템을 IoT로 시뮬레이션(구현)하는게 목표라 타워 크레인, 선박등을 제작해야합니다. 여러 이점때문에 3D 프린터를 이용하고 싶은데 학교에 학생들이 이용할 수 있는 3D 프린터기가 있는지 궁금합니다.

```

이런 내용으로 방금 교수님께 이메일(강의계획서에 나온 이메일) 보냈습니다.

**Comment by seonghwan7694** [comment]
답변왔습니다!

했던 질문은 이전에 올린 것이고 이메일로 온 답변만 첨부하겠습니다!

```c
Q1. 괜찮습니다.

Q2. 마찬가지로 괜찮습니다.!

A3. 3D 프린터는 공학센터에 하나 있습니다. 우리학교 공학교육혁신센터에 연락을 하셔서, 소프트웨어학부 / 창의적공학설계
수업을 듣는 학생이라고 하면, 어떻게 하면 된다라고 가이드를 해줄겁니다.

김영종.

/*
 Youngjong Kim, Ph.D.
 Associate professor in Software at  Soongsil University

 mobile: +82-10-5241-5332, phone: +82-2-828-7338
 email: [opensys@soongsil.ac.kr](mailto:opensys@soongsil.ac.kr)
*/
```

3D 프린터기가 이용가능하다니 정말 정말 정말 행복하네요 ㅋㅋㅋㅋㅋㅋ

**Comment by seonghwan7694** [comment]
[오드로이드 C4](https://www.hardkernel.com/ko/shop/odroid-c4/)로 결론이 났습니다.
