### ISSUE TITLE
[회의 보고서] 9월 26일

### ISSUE THREAD

**Issue by seonghwan7694** [seonghwan7694/Marine_City#9]
*모든 단위는 cm 입니다.
1. 맵 크기
40 * 65 * 15 (가로, 세로, 높이) X 3개
65 * 65 * 15 (가로, 세로, 높이) X 1개

2. 타워 크레인
3. 라즈베리파이 or ODROID : 
4. [360도 회전이 가능한 모터](https://smartstore.naver.com/makerspace/products/4488493669?)
5. 공유기 : https://www.devicemart.co.kr/goods/view?no=14555480
6. 중앙 제어 보드 :  [ODROID-C4](https://www.hardkernel.com/ko/shop/odroid-c4/)
7. [MicroSDHC 8GB](https://www.devicemart.co.kr/goods/view?no=10945150)

**Comment by mokyabun** [comment]
[무한회전 서보모터](https://smartstore.naver.com/makerspace/products/4488493669?NaPm=ct%3Dl8ipzcxs%7Cci%3D12ed3080a28fe5f9b115ba4ee65685809d8a68b7%7Ctr%3Dslsl%7Csn%3D525290%7Chk%3Dad86035ea54b7013d71abb25f7bbab444b8f3826)

**Comment by mokyabun** [comment]
[LOLIN D1](https://smartstore.naver.com/misoparts/products/6611022099?NaPm=ct%3Dl8iqeq6g%7Cci%3D88da28fd02ab2c0f1bf79045da86b87d83d78922%7Ctr%3Dslsl%7Csn%3D1956020%7Chk%3D88ad7fe792860ef65f08f56ab9da02a6f2cb8e37)

**Comment by seonghwan7694** [comment]
### 배송비 미 포함, 부가세 미 포함(디바이스 마켓이 부과세를 매기깁니다) 가격입니다

1. [전자석 모듈](https://www.devicemart.co.kr/goods/view?no=1382905) * 3개 = 29,700
2. [아두이노 WeMos D1 MINI 우노 WIFI ESP8266 보드](https://smartstore.naver.com/misoparts/products/6611022099?) * 9개 = 28,170
3. [공유기](https://www.devicemart.co.kr/goods/view?no=14555480) * 1개 = 15,500
4. [무한 회전 - 서보 모터](https://smartstore.naver.com/makerspace/products/4488493669?) * 25개 = 60,000
5. [아크릴 판](https://smartstore.naver.com/sellacrylic/products/5762492997?NaPm=ct%3Dl8iqqhsg%7Cci%3D24dfeb46c2f42d3ca9572fdb60cdf2ff492cab4b%7Ctr%3Dsls%7Csn%3D3736569%7Chk%3De756a279bc62aad884543a202e427d758eb0dc24) 1개 = 69,000

총 가격 : 202,370 (배송비, 부과세 미포함)

판단 부탁드립니다 🙏🙏🙏

**Comment by mokyabun** [comment]
이슈 #10 #11 #12 #13 로 이동
